name: Deploy Simple App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: login to docker registry
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    
    - name: build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: nikymn/frontend-dumbmerch:2.3

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - name: ssh to deploy server
      uses: appleboy/ssh-action@master
      with:
        host: 19.168.20.21
        username: deploy
        password: ${{ secrets.PASSWORD }}
        port: 
        script: |
          docker pull nikymn/frontend-dumbmerch:latest
          docker stop frontend-dumbmerch
          docker rm frontend-dumbmerch
          docker run -d --name frontend-dumbmerch -p 3000:3000 nikymn/frontend-dumbmerch:latest
